# Generated by Django 4.2 on 2023-06-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('CellId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Round', models.IntegerField(blank=True, verbose_name='round')),
                ('NameMagic', models.CharField(blank=True, max_length=100, verbose_name='nameMagic')),
                ('CubeMagic', models.IntegerField(blank=True, verbose_name='cubeMagic')),
                ('TypeCubeMagic', models.IntegerField(blank=True, verbose_name='typeCubeMagic')),
                ('DamageMagic', models.IntegerField(blank=True, verbose_name='damageMagic')),
                ('Complexity', models.IntegerField(blank=True, verbose_name='сomplexity')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('CharacterId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='charId')),
                ('Inventory', models.CharField(blank=True, max_length=10000, verbose_name='inventory')),
                ('Cell', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PathBase.cell', verbose_name='cell')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('DescriptionId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('Alignment', models.CharField(blank=True, max_length=3000, verbose_name='alignment')),
                ('God', models.CharField(blank=True, max_length=100, verbose_name='god')),
                ('Country', models.CharField(blank=True, max_length=50, verbose_name='country')),
                ('Race', models.CharField(blank=True, max_length=30, verbose_name='race')),
                ('Size', models.CharField(blank=True, max_length=30, verbose_name='size')),
                ('Age', models.CharField(blank=True, max_length=10, verbose_name='age')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('MoneyId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('CM', models.IntegerField(blank=True, verbose_name='Copper')),
                ('SM', models.IntegerField(blank=True, verbose_name='Silver')),
                ('GM', models.IntegerField(blank=True, verbose_name='Gold')),
                ('PM', models.IntegerField(blank=True, verbose_name='Platinum')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('StatId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Strength', models.IntegerField(blank=True, verbose_name='strength')),
                ('Dexterity', models.IntegerField(blank=True, verbose_name='dexterity')),
                ('Constitution', models.IntegerField(blank=True, verbose_name='constitution')),
                ('Intelligence', models.IntegerField(blank=True, verbose_name='intelligence')),
                ('Wisdom', models.IntegerField(blank=True, verbose_name='wisdom')),
                ('Charisma', models.IntegerField(blank=True, verbose_name='charisma')),
                ('Speed', models.IntegerField(blank=True, verbose_name='speed')),
                ('HP', models.IntegerField(blank=True, verbose_name='hp')),
                ('Time_hp', models.IntegerField(blank=True, verbose_name='time_hp')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('WeaponId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('NameWeapon', models.CharField(blank=True, max_length=100, verbose_name='nameWeapon')),
                ('CubeWeapon', models.IntegerField(blank=True, verbose_name='cubeWeapon')),
                ('TypeCubeWeapon', models.IntegerField(verbose_name='typeCubeWeapon')),
                ('DamageWeapon', models.IntegerField(blank=True, verbose_name='damageWeapon')),
                ('CritWeapon', models.IntegerField(blank=True, verbose_name='critWeapon')),
                ('TypeWeapon', models.BooleanField(blank=True, verbose_name='typeWeapon')),
                ('Ammo', models.IntegerField(blank=True, verbose_name='ammo')),
                ('Bonus', models.IntegerField(blank=True, verbose_name='Bonus')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='userId')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SessionId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='sessionId')),
                ('NameSession', models.CharField(max_length=60, verbose_name='nameSession')),
                ('UserStatus', models.CharField(blank=True, max_length=100, verbose_name='userStatus')),
                ('CharacterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PathBase.character', verbose_name='character')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PathBase.user', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='Description',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PathBase.description', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='character',
            name='Money',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PathBase.money', verbose_name='money'),
        ),
        migrations.AddField(
            model_name='character',
            name='Stat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PathBase.stat', verbose_name='stat'),
        ),
        migrations.AddField(
            model_name='character',
            name='Weapon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PathBase.weapon', verbose_name='weapon'),
        ),
    ]
